"""
send_email.py
─────────────────────────────────────────────────────
Gmail SMTP로 다이제스트 메일 발송.
"""

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def build_digest_html(summaries: list[dict]) -> str:
    """요약 리스트를 HTML 메일 본문으로 조립."""
    today = datetime.now().strftime("%Y년 %m월 %d일 (%a)")
    
    if not summaries:
        body_inner = "<p>오늘은 신규 영상이 없습니다.</p>"
    else:
        items = []
        for s in summaries:
            # 줄바꿈을 <br>로 변환
            summary_html = s["summary"].replace("\n", "<br>")
            item = f"""
            <div style="margin-bottom: 36px; padding: 20px; background: #fafafa; border-left: 4px solid #2563eb; border-radius: 4px;">
                <div style="font-size: 12px; color: #6b7280; margin-bottom: 8px;">
                    📺 {s['channel_name']}
                    &nbsp;·&nbsp;
                    📝 자막 출처: <code style="background:#eee;padding:2px 6px;border-radius:3px;">{s['transcript_source']}</code>
                </div>
                <h3 style="margin: 0 0 12px 0; font-size: 16px; color: #111;">
                    <a href="{s['url']}" style="color: #2563eb; text-decoration: none;">
                        {s['title']}
                    </a>
                </h3>
                <div style="font-size: 14px; line-height: 1.7; color: #333;">
                    {summary_html}
                </div>
                <div style="margin-top: 12px;">
                    <a href="{s['url']}" style="font-size: 12px; color: #6b7280;">
                        ▶ 원본 영상 보기
                    </a>
                </div>
            </div>
            """
            items.append(item)
        body_inner = "\n".join(items)
    
    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family: -apple-system, 'Noto Sans KR', sans-serif; max-width: 720px; margin: 0 auto; padding: 24px; background: #fff;">
    <div style="border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px;">
        <h1 style="margin: 0; font-size: 22px; color: #111;">📊 YouTube Digest</h1>
        <p style="margin: 4px 0 0 0; color: #6b7280; font-size: 14px;">
            {today} &nbsp;·&nbsp; 총 {len(summaries)}편
        </p>
    </div>
    {body_inner}
    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af;">
        Auto-generated by youtube-digest · Powered by Gemini
    </div>
</body>
</html>"""
    return html


def send_digest_email(
    summaries: list[dict],
    gmail_address: str,
    gmail_app_password: str,
    recipient: str = None,
):
    """
    다이제스트 메일 발송.
    
    Args:
        summaries: [{title, channel_name, url, summary, transcript_source}, ...]
        gmail_address: 발신자 Gmail 주소
        gmail_app_password: 16자 앱 비밀번호
        recipient: 수신자 (기본값: 본인에게)
    """
    if recipient is None:
        recipient = gmail_address
    
    today = datetime.now().strftime("%Y-%m-%d")
    subject = f"[YouTube Digest] {today} — {len(summaries)}편"
    
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_address
    msg["To"] = recipient
    
    html_body = build_digest_html(summaries)
    msg.attach(MIMEText(html_body, "html", "utf-8"))
    
    print(f"[send_email] Gmail SMTP 연결 중...")
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_address, gmail_app_password)
            server.send_message(msg)
        print(f"[send_email] ✅ 메일 발송 완료 → {recipient}")
    except Exception as e:
        print(f"[send_email] ❌ 발송 실패: {type(e).__name__}: {e}")
        raise


if __name__ == "__main__":
    # 단독 실행 시 테스트
    import os
    test_summaries = [{
        "title": "테스트 영상 제목",
        "channel_name": "테스트 채널",
        "url": "https://youtube.com/watch?v=test",
        "summary": "【한 줄 요약】\n테스트입니다.\n\n【핵심 포인트】\n1. 첫 번째\n2. 두 번째",
        "transcript_source": "youtube-transcript-api",
    }]
    send_digest_email(
        summaries=test_summaries,
        gmail_address=os.environ["GMAIL_ADDRESS"],
        gmail_app_password=os.environ["GMAIL_APP_PASSWORD"],
    )
